### ISSUE TITLE
Getting started w/ Nuttx

### ISSUE THREAD

**Issue by eden-desta** [micro-ROS/micro_ros_nuttx_app#13]
Hi folks,
Just a few questions:

In order to work with this version of nuttx, do we not go through the standard setup procedures that we did with Zephyr and FreeRTOS. (if not how do we go about generating the firmware files. If we should be then there is a potential problem with the setup script). 

Additionally, and this is a larger question and I can take the time to parse through this -- but can this be plug and play for any board or do we have to go through and provide the necessary files like we did previously with Zephyr and FreeRTOS

**Comment by pablogs9** [comment]
Hello @eden-desta,

I'm not sure about understanding your questions... This is a standalone package for including micro-ROS in a Nuttx environment. You just need to add this repo to your app folder. Let me know if the README.md is clear enough. In short, we do not need the `micro_ros_setup` scripts anymore, and micro-ROS is being integrated directly in the build procedure of Nuttx 10.

In general, this repo has been tested with the STM32L4 Discovery kit IoT node but it should work with any Nuttx compatible board. Please let me know which is your setup and we will help you in the procedure.

Does this answers your questions?

**Comment by eden-desta** [comment]
Ah yes, this answers my questions! Okay copy. Apologies my understanding was that it would function similar to the other RTOSes. Perfect, and good note will definitely test it with my boards then, they are definitely Nuttx compatible. Thank you @pablogs9 !!
