### ISSUE TITLE
Suggestion on the directory structure for codes

### ISSUE THREAD

**Issue by Barry-Xu-2018** [micro-ROS/micro_ros_nuttx_app#20]
In current codes, the building of example codes and micro-ros library is handled in one Makefile.    
Normally, user doesn't care building step of micro-ros library.   
So I think it is better to split current codes as  below:
```
micro_ros_nuttx_app
    |-- ...
    |-- example_app/       <= User can check the contents of this directoy to understand how to 
    |          |                                 create his program. 
    |          |-- ...
    |-- micro_ros_lib/      <= User  need not  to care this directory.
               |-- ...

```
The menuconfig likes as below 
```
Application Configuration
      --->  micro-ROS library and app 
               -->  [*] micro-ROS example app
                     [*] micro-ROS library
                                                            
```

There is a  quick implementation to help my idea.  
https://github.com/Barry-Xu-2018/micro_ros_nuttx_app/tree/topic-reorganized-codes

**Comment by Barry-Xu-2018** [comment]
@pablogs9 

I have a suggestion for the current directory structure and hear your opinion.

**Comment by pablogs9** [comment]
Hello @Barry-Xu-2018, for sure this is a great idea and highly improves the readability of this example repo.

Could you please open a PR, so we can check and test it and merge the changes?

Thanks a lot for the contribution.

CC: @Acuadros95

**Comment by Barry-Xu-2018** [comment]
@pablogs9 

Thanks. I made PR #21.   
Please review it.
